# Generated by Django 2.2.5 on 2021-06-12 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catgory_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=255)),
                ('release_date', models.DateField(auto_now_add=True)),
                ('cat_slug', models.SlugField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='coverimgapi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField(auto_now_add=True)),
                ('channel_logo', models.FileField(blank=True, upload_to='coverimg')),
            ],
        ),
        migrations.CreateModel(
            name='nbox_ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('ad_img', models.FileField(blank=True, upload_to='coverimg')),
            ],
        ),
        migrations.CreateModel(
            name='post_models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255)),
                ('channel_slug', models.SlugField(max_length=200)),
                ('release_date', models.DateField(auto_now_add=True)),
                ('straming_url', models.URLField(default='www.test.com')),
                ('channel_logo', models.FileField(blank=True, upload_to='channel_logo')),
                ('catgory', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Data_app.catgory_list')),
            ],
        ),
    ]
