# Generated by Django 2.2.5 on 2020-07-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0002_coverimg_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='target_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_links', models.CharField(max_length=100)),
            ],
        ),
    ]
