# Generated by Django 2.2.5 on 2020-07-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0003_target_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag_createors',
            name='main_tag_select',
        ),
        migrations.AddField(
            model_name='tag_createors',
            name='tagSlug',
            field=models.SlugField(default='emty', max_length=233),
        ),
    ]
