# Generated by Django 2.2.5 on 2020-07-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0005_tag_createors_tagnamebg'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcreate',
            name='SeoTitle',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AddField(
            model_name='postcreate',
            name='SeoimgTitle',
            field=models.CharField(blank=True, max_length=155),
        ),
    ]
