# Generated by Django 2.2.5 on 2020-07-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0006_auto_20200728_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcreate',
            name='SeoMetaDes',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='postcreate',
            name='SeoimgTitle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
