# Generated by Django 2.2.5 on 2020-07-29 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0007_auto_20200729_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcreate',
            old_name='SeoimgTitle',
            new_name='Seoimgalt',
        ),
    ]
