# Generated by Django 2.2.5 on 2020-08-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0009_postcreate_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cetagroy_list',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ownercontents',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tag_createors',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tag_data',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
