# Generated by Django 2.2.5 on 2020-08-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0010_auto_20200803_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcreate',
            name='content_typeModel',
            field=models.CharField(choices=[('Content_type', (('MA', 'Morocco'), ('DZ', 'Algeria')))], default='Content_tye', max_length=300),
        ),
    ]
