# Generated by Django 2.2.5 on 2020-08-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0013_auto_20200803_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcreate',
            name='content_typeModel',
            field=models.CharField(blank=True, choices=[('O', 'Me'), ('F', 'Friends'), ('P', 'Public')], default='P', max_length=1),
        ),
    ]
