# Generated by Django 2.2.5 on 2020-08-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0014_auto_20200803_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcreate',
            name='content_typeModel',
            field=models.CharField(blank=True, choices=[('s', 'Specfiction'), ('r', 'Review')], default='r', max_length=1),
        ),
    ]
