# Generated by Django 2.2.5 on 2020-08-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0015_auto_20200804_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hot_ThsMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ListMonth', models.ManyToManyField(default='0', to='Data_app.PostCreate')),
            ],
        ),
    ]
