# Generated by Django 2.2.5 on 2020-08-21 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0018_auto_20200807_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag_createors',
            name='selet_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Data_app.tag_data'),
        ),
    ]
