# Generated by Django 2.2.5 on 2020-10-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0021_auto_20201003_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownercontents',
            name='keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='postcreate',
            name='keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ownercontents',
            name='authorsweblink',
            field=models.URLField(blank=True),
        ),
    ]
