# Generated by Django 2.2.5 on 2020-10-10 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0022_auto_20201010_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownercontents',
            name='coverImg',
        ),
        migrations.RemoveField(
            model_name='ownercontents',
            name='focus_keyword',
        ),
    ]
