# Generated by Django 2.2.5 on 2021-05-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0023_auto_20201010_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='catgory_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=255)),
                ('release_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='post_models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255)),
                ('channel_slug', models.SlugField(max_length=200)),
                ('release_date', models.DateField(auto_now_add=True)),
                ('channel_logo', models.URLField(max_length=400)),
                ('catgory', models.ManyToManyField(blank=True, to='Data_app.catgory_list')),
            ],
        ),
        migrations.DeleteModel(
            name='Cetagroy_list',
        ),
        migrations.DeleteModel(
            name='CoverImg',
        ),
        migrations.RemoveField(
            model_name='hot_thsmonth',
            name='ListMonth',
        ),
        migrations.RemoveField(
            model_name='postcreate',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='postcreate',
            name='contentowners',
        ),
        migrations.RemoveField(
            model_name='postcreate',
            name='selete_channel_tag',
        ),
        migrations.RemoveField(
            model_name='postcreate',
            name='tag_creator',
        ),
        migrations.RemoveField(
            model_name='tag_createors',
            name='selet_channel',
        ),
        migrations.RemoveField(
            model_name='tag_data',
            name='tag_channel_name',
        ),
        migrations.DeleteModel(
            name='target_link',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.DeleteModel(
            name='Hot_ThsMonth',
        ),
        migrations.DeleteModel(
            name='Ownercontents',
        ),
        migrations.DeleteModel(
            name='PostCreate',
        ),
        migrations.DeleteModel(
            name='tag_createors',
        ),
        migrations.DeleteModel(
            name='tag_data',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
