# Generated by Django 2.2.5 on 2021-05-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0024_auto_20210525_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_models',
            name='channel_logo',
            field=models.ImageField(blank=True, upload_to='channel_logo'),
        ),
    ]
