# Generated by Django 2.2.5 on 2021-05-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0025_auto_20210525_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_models',
            name='straming_url',
            field=models.URLField(default='www.test.com'),
        ),
    ]
