# Generated by Django 2.2.5 on 2021-05-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0026_post_models_straming_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='catgory_list',
            name='cat_slug',
            field=models.SlugField(default=6, max_length=200),
            preserve_default=False,
        ),
    ]
