# Generated by Django 2.2.5 on 2021-05-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0027_catgory_list_cat_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='coverimgapi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField(auto_now_add=True)),
                ('channel_logo', models.ImageField(blank=True, upload_to='coverimg')),
            ],
        ),
    ]
